### ISSUE TITLE
subsequent betting after flop does not reduce balance

### ISSUE THREAD

**Issue by redacted24** [redacted24/poker#15]
**Describe the bug**
Bets after flop (board cards are shown) does not reduce player balance

**To Reproduce**
1. Start website
2. Do whatever in the pre-flop
3. When in flop, try betting any amount

**Expected behavior**
The bet should reduce player amount. However, the displayed player balance is still the same

**Screenshots**
**Before:**
![image](https://github.com/redacted24/poker/assets/46847115/8cea239d-9045-493b-bb11-f56434fa8147)

**After:**
![image](https://github.com/redacted24/poker/assets/46847115/18a1bcea-31eb-4496-831c-dabf85fd4809)

**Comment by Crazydodo123** [comment]
All bets after preflop is turned into calls because of betting cap. The betting cap does not acurately represent the actual betting cap of the table. 
![image](https://github.com/redacted24/poker/assets/109930286/241c28e2-a384-4d69-b4dd-f610b838a1f8)

**Comment by redacted24** [comment]
Understood, will plan on fixing

**Comment by redacted24** [comment]
@Crazydodo123 Could you test on frontend and check if this is still an issue? I dunno how to run the front end with the 2 servers

**Comment by redacted24** [comment]
Works on frontend. Perfect
