### ISSUE TITLE
setting advancedbot as a computer in frontend breaks the game

### ISSUE THREAD

**Issue by redacted24** [redacted24/poker#19]
**Describe the bug**
In poker.py I replaced ScaryCat with AdvancedBot as a computer, but it doesn't work.

**To Reproduce**
_Checkout to bots branch_

1. table.add_player(AdvancedBot('computer1', table, 'moderate'))
2. Remove ScaryCat bot
3. Run app in frontend

**Expected behavior**
There should only be two opposing players and they should have 2 cards each

**Screenshots**
_**Replacing Scary Cat with Advanced Bot**_
![image](https://github.com/redacted24/poker/assets/46847115/bc3a4f01-7cca-4799-8f32-54c11a1e4f8a)

_**What the Screen Shows**_
![image](https://github.com/redacted24/poker/assets/46847115/5e05fe23-7048-44a9-b798-36bac89ff7e2)

**Additional context**
**_Error Message_**
![image](https://github.com/redacted24/poker/assets/46847115/80ed44e2-6d6e-4687-a2bd-a37680cea2ad)
![image](https://github.com/redacted24/poker/assets/46847115/1d6eb461-e45b-404a-acd9-828baebb955b)

**Comment by Crazydodo123** [comment]
fixed in latest commit on bots branch
