### ISSUE TITLE
Advanced bots stuck in infinite loop

### ISSUE THREAD

**Issue by Crazydodo123** [redacted24/poker#20]
**Describe the bug**
Very rarely, a table with more than 1 advanced bot will get stuck in an infinite loop betting loop. 

**To Reproduce**
1. Go to the latest bots branch
2. Uncomment line 222
3. Run bot_tests.py in /tests folder
5. See error

**Expected behavior**
The table should not allow bots to keep betting the same amount. 

**Screenshots**
![image](https://github.com/redacted24/poker/assets/109930286/df24ea5e-2ebc-4d01-a0b2-0ad8b1531467)

**Comment by redacted24** [comment]
I think its an issue with make4 strategy if both bots have very strong hands I'll look into it

**Comment by redacted24** [comment]
With backend betting cap fix this shouldn't happen anymore. Let's go!
